/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package latihan6;

import java.util.Enumeration;
import javax.swing.AbstractButton;

/**
 *
 * @author SB604-8
 */
public class KalkulatorForm3 extends javax.swing.JFrame {

    /**
     * Creates new form KalkulatorForm3
     */
    public KalkulatorForm3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupOperasi = new javax.swing.ButtonGroup();
        lblBilangan1 = new javax.swing.JLabel();
        txtFieldBil1 = new javax.swing.JTextField();
        lblBilangan2 = new javax.swing.JLabel();
        lblHasil = new javax.swing.JLabel();
        txtFieldBil2 = new javax.swing.JTextField();
        btnProses = new javax.swing.JButton();
        rBtnTambah = new javax.swing.JRadioButton();
        rBtnKali = new javax.swing.JRadioButton();
        rBtnKurang = new javax.swing.JRadioButton();
        rBtnBagi = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblBilangan1.setText("Bilangan 1 :");

        txtFieldBil1.setColumns(10);

        lblBilangan2.setText("Bilangan 2 :");

        lblHasil.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHasil.setText("0");

        txtFieldBil2.setColumns(10);

        btnProses.setText("Proses");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });

        btnGroupOperasi.add(rBtnTambah);
        rBtnTambah.setText("Tambah");

        btnGroupOperasi.add(rBtnKali);
        rBtnKali.setText("Kali");

        btnGroupOperasi.add(rBtnKurang);
        rBtnKurang.setText("Kurang");

        btnGroupOperasi.add(rBtnBagi);
        rBtnBagi.setText("Bagi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rBtnTambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rBtnKali)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rBtnKurang)
                                .addGap(6, 6, 6)
                                .addComponent(rBtnBagi))
                            .addComponent(lblBilangan1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnProses)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblBilangan2)
                                    .addGap(49, 49, 49)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtFieldBil2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtFieldBil1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(177, 199, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(lblHasil)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBilangan1)
                    .addComponent(txtFieldBil1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBilangan2)
                    .addComponent(txtFieldBil2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rBtnTambah)
                    .addComponent(rBtnKali))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rBtnKurang)
                    .addComponent(rBtnBagi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(btnProses)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHasil)
                .addGap(101, 101, 101))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        // TODO add your handling code here:
        String selectedRadioButton = null;
                String operasi;
        int bil1 = Integer.parseInt(txtFieldBil1.getText());
        int bil2 = Integer.parseInt(txtFieldBil2.getText());
        for (Enumeration<AbstractButton> buttons = btnGroupOperasi.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();
            if (button.isSelected()) {
                selectedRadioButton = button.getText();
            }
        }
        
        if (selectedRadioButton.equals("Tambah")) {
            
            int hasilbil = bil1 + bil2;
            lblHasil.setText(Integer.toString(hasilbil));
            
        } else if (selectedRadioButton.equals("Kurang")) {
            
            int hasilbil = bil1 - bil2;
            lblHasil.setText(Integer.toString(hasilbil));
            
        } else if (selectedRadioButton.equals("Kali")) {
            
            int hasilbil = bil1 * bil2;
            lblHasil.setText(Integer.toString(hasilbil));
            
        } else if (selectedRadioButton.equals("Bagi")) {
            
            int hasilbil = bil1 / bil2;
            lblHasil.setText(Integer.toString(hasilbil));
            
        }
    }//GEN-LAST:event_btnProsesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KalkulatorForm3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KalkulatorForm3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KalkulatorForm3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KalkulatorForm3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KalkulatorForm3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupOperasi;
    private javax.swing.JButton btnProses;
    private javax.swing.JLabel lblBilangan1;
    private javax.swing.JLabel lblBilangan2;
    private javax.swing.JLabel lblHasil;
    private javax.swing.JRadioButton rBtnBagi;
    private javax.swing.JRadioButton rBtnKali;
    private javax.swing.JRadioButton rBtnKurang;
    private javax.swing.JRadioButton rBtnTambah;
    private javax.swing.JTextField txtFieldBil1;
    private javax.swing.JTextField txtFieldBil2;
    // End of variables declaration//GEN-END:variables
}
