/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package latihan6;

import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;

/**
 *
 * @author SB604-8
 */
public class KalkulatorForm3 extends javax.swing.JFrame {

    /**
     * Creates new form HelloWorldForm
     */
    public KalkulatorForm3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrup = new javax.swing.ButtonGroup();
        lblBilangan1 = new javax.swing.JLabel();
        txtInputSatu = new javax.swing.JTextField();
        lblHasil = new javax.swing.JLabel();
        lblBilangan2 = new javax.swing.JLabel();
        txtInputDua = new javax.swing.JTextField();
        btnProses = new javax.swing.JButton();
        rbTambah = new javax.swing.JRadioButton();
        rbKurang = new javax.swing.JRadioButton();
        rbKali = new javax.swing.JRadioButton();
        rbBagi = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblBilangan1.setText("Input Bilangan 1");

        txtInputSatu.setColumns(20);

        lblHasil.setText("Hasil");

        lblBilangan2.setText("Input Bilangan 2");

        txtInputDua.setColumns(20);

        btnProses.setText("Proses");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });

        btnGrup.add(rbTambah);
        rbTambah.setText("Tambah");
        rbTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTambahActionPerformed(evt);
            }
        });

        btnGrup.add(rbKurang);
        rbKurang.setText("Kurang");

        btnGrup.add(rbKali);
        rbKali.setText("Kali");

        btnGrup.add(rbBagi);
        rbBagi.setText("Bagi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnProses)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblHasil)
                        .addGap(103, 103, 103))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBilangan1)
                            .addComponent(lblBilangan2))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rbTambah)
                                .addComponent(txtInputDua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtInputSatu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbKurang)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbKali)
                                    .addComponent(rbBagi))))
                        .addContainerGap(48, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBilangan1)
                    .addComponent(txtInputSatu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBilangan2)
                    .addComponent(txtInputDua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbTambah)
                    .addComponent(rbKali))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbKurang)
                    .addComponent(rbBagi))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHasil)
                    .addComponent(btnProses))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        String selectedRadioButton = null;
        int hasil;
        int bilanganSatu = Integer.valueOf(txtInputSatu.getText());
        int bilanganDua = Integer.valueOf(txtInputDua.getText());
        
        for (Enumeration<AbstractButton> buttons =
            btnGrup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                selectedRadioButton = button.getText();
                } else if (rbTambah.isSelected()) {
                hasil = bilanganSatu + bilanganDua;
                String akhir = Integer.toString(hasil);
                lblHasil.setText(akhir);
                } else if (rbKurang.isSelected()) {
                hasil = bilanganSatu - bilanganDua;
                String akhir = Integer.toString(hasil);
                lblHasil.setText(akhir);
                } else if (rbKali.isSelected()) {
                hasil = bilanganSatu * bilanganDua;
                String akhir = Integer.toString(hasil);
                lblHasil.setText(akhir);
                } else if (rbBagi.isSelected()) {
                hasil = bilanganSatu / bilanganDua;
                String akhir = Integer.toString(hasil);
                lblHasil.setText(akhir);
                }
            } 
       
    }//GEN-LAST:event_btnProsesActionPerformed

    private void rbTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTambahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbTambahActionPerformed
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KalkulatorForm3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KalkulatorForm3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KalkulatorForm3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KalkulatorForm3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KalkulatorForm3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGrup;
    private javax.swing.JButton btnProses;
    private javax.swing.JLabel lblBilangan1;
    private javax.swing.JLabel lblBilangan2;
    private javax.swing.JLabel lblHasil;
    private javax.swing.JRadioButton rbBagi;
    private javax.swing.JRadioButton rbKali;
    private javax.swing.JRadioButton rbKurang;
    private javax.swing.JRadioButton rbTambah;
    private javax.swing.JTextField txtInputDua;
    private javax.swing.JTextField txtInputSatu;
    // End of variables declaration//GEN-END:variables
}
