/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package latihan3;

import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;

/**
 *
 * @author SB604-8
 */
public class MahasiswaForm extends javax.swing.JFrame {

    /**
     * Creates new form HelloWorldForm
     */
    public MahasiswaForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrup = new javax.swing.ButtonGroup();
        btnHasil = new javax.swing.JButton();
        lblNama = new javax.swing.JLabel();
        txtInput = new javax.swing.JTextField();
        lblKemampuan = new javax.swing.JLabel();
        cbJava = new javax.swing.JCheckBox();
        cbJavascript = new javax.swing.JCheckBox();
        cbPHP = new javax.swing.JCheckBox();
        cbPhyton = new javax.swing.JCheckBox();
        lblUniversitas = new javax.swing.JLabel();
        cbUniversitas = new javax.swing.JComboBox<>();
        lblKelamin = new javax.swing.JLabel();
        rbLaki = new javax.swing.JRadioButton();
        rbPerempuan = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnHasil.setText("Submit");
        btnHasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHasilActionPerformed(evt);
            }
        });

        lblNama.setText("Nama :");

        txtInput.setColumns(20);

        lblKemampuan.setText("Kemampuan");

        cbJava.setText("Java");

        cbJavascript.setText("Javascript");

        cbPHP.setText("PHP");

        cbPhyton.setText("Phyton");

        lblUniversitas.setText("Universitas :");

        cbUniversitas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Universitas Pasundan", "Institut Teknologi Bandung", "Universitas Pendidikan Indonesia", "Universitas Padjadjaran" }));

        lblKelamin.setText("Jenis Kelamin");

        btnGrup.add(rbLaki);
        rbLaki.setText("Laki-Laki");

        btnGrup.add(rbPerempuan);
        rbPerempuan.setText("Perempuan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHasil)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNama)
                            .addComponent(lblKemampuan)
                            .addComponent(lblUniversitas)
                            .addComponent(lblKelamin))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbUniversitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbJava)
                                    .addComponent(cbJavascript)
                                    .addComponent(rbLaki))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbPerempuan)
                                    .addComponent(cbPhyton)
                                    .addComponent(cbPHP))))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNama)
                    .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblKemampuan)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbJava)
                        .addComponent(cbPHP)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbJavascript)
                    .addComponent(cbPhyton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUniversitas)
                    .addComponent(cbUniversitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKelamin)
                    .addComponent(rbLaki)
                    .addComponent(rbPerempuan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHasil)
                .addGap(97, 97, 97))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHasilActionPerformed
            String nama = null;
            boolean kJava, kJavascript, kPhp, kPython;
            String universitas;
            String selectedRadioButton = null;
            String pesan ;
            // Get nama
            nama = txtInput.getText();
            // Get Kemampuan
            kJava = cbJava.isSelected();
            kJavascript = cbJavascript.isSelected();
            kPhp = cbPHP.isSelected();
            kPython = cbPhyton.isSelected();
            // Get Universitas
            universitas = cbUniversitas.getSelectedItem().toString();
            // Get selected Radio Button
            for (Enumeration<AbstractButton> buttons =
            btnGrup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
            selectedRadioButton = button.getText();
                } 
            } 
             pesan = "Hello " + nama + ", kuliah di "  + universitas + " kemampuan yang dimiliki yaitu : "
            + ((kJava == true) ? "java, " : "")+((kJavascript == true) ?
            "javascript, " : "") + ((kPhp == true) ? "php, " : "")+ ((kPython == true) ?
            "Python." : "")+" Anda adalah seorang : "+selectedRadioButton;
           
            JOptionPane.showMessageDialog(null, pesan);

    }//GEN-LAST:event_btnHasilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MahasiswaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MahasiswaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MahasiswaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MahasiswaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MahasiswaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGrup;
    private javax.swing.JButton btnHasil;
    private javax.swing.JCheckBox cbJava;
    private javax.swing.JCheckBox cbJavascript;
    private javax.swing.JCheckBox cbPHP;
    private javax.swing.JCheckBox cbPhyton;
    private javax.swing.JComboBox<String> cbUniversitas;
    private javax.swing.JLabel lblKelamin;
    private javax.swing.JLabel lblKemampuan;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblUniversitas;
    private javax.swing.JRadioButton rbLaki;
    private javax.swing.JRadioButton rbPerempuan;
    private javax.swing.JTextField txtInput;
    // End of variables declaration//GEN-END:variables
}
